In [6]:
def test():
    print('test()for function')
    return
test()
            
            

test()for function


In [9]:

class Demo:
        def test(self):
            print("test() for the class and method")
            return
obj=Demo()
obj.test()
            
            

test() for the class and method


In [11]:
class Demo1:
    def fact(self,n):
        return
p1=Demo1()
p1.fact(5)

In [15]:
class Demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n = n - 1
        return fact
p=Demo1()
print(p.fact(5))

120


In [16]:
class Demo:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo(10,20)
print(c1.add(100,200))

300


# derived class

In [24]:
class person(object):
    def __init__(self,name):
        self.name=name
    def getname(self):
            return self.name
    def isemployee(self):
        return False
class employee(person):
    def isemployee(self):
        return True
emp=person("anil")
print(emp.getname(),emp.isemployee())
emp1=person("arun")
print(emp1.getname(),emp1.isemployee())



anil False
arun False


# python numpy

In [10]:
import numpy as np
list1=[1,2,3,4]
array=np.array(list1)
print(array)

[1 2 3 4]


In [14]:
list1=[1,2,3,4]
array=np.array(list1)
print(array.shape)
print(array.dtype)


(4,)
int32


In [12]:

a = np.array([(1,2,3),(4,5,6)])
print(a)
a.reshape(1,3,2)

[[1 2 3]
 [4 5 6]]


array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [19]:
a = np.array([(1,2,3),(4,5,6)])
print("second row: ",a[1])

second row:  [4 5 6]


In [18]:
a = np.array([(1,2,3),(4,5,6)])
print("slicing row: ",a[:,1])

slicing row:  [2 5]


In [17]:
a = np.array([(1,2,3),(4,5,6)])
print("slicing last  column: ",a[:,2])

slicing last  column:  [3 6]


In [21]:
a = np.array([(1,2,3),(4,5,6)])
print("row and column: ",a[1,:2])

row and column:  [4 5]


In [30]:
s =np.random.normal(4,1,6)
print(s)
print("min value=",np.min(s))
print("max value=" , np.max(s))
print("mean value=",np.mean(s))
print("median value=",np.median(s))

[4.70634563 4.01002781 3.7578343  3.24659981 2.71884437 1.21253929]
min value= 1.2125392879511998
max value= 4.706345634481463
mean value= 3.275365200968157
median value= 3.5022170529294447


In [39]:
import pandas as pd
li=["rolno","name","age"]
li2=[[1,2,3],['dhoni','gayle','warner'],[18,34,56]]
new=dict(zip(li,li2))
new
x=pd.DataFrame(new)
x

rolno    name  age
0      1   dhoni   18
1      2   gayle   34
2      3  warner   56